### ISSUE TITLE
Enhancement: Center the workspace thumbnails.

### ISSUE THREAD

**Issue by SaucySauce** [RensAlthuis/vertical-overview#1]

**Comment by romgrk** [comment]
I was going to propose to have the thumbnails like they were in 3.38 but I'll comment here because it's a similar issue. It would be nice to have because when used in conjunction with hide-top-bar, the thumbnail position shifts when going into overview and it feels janky. Also I really liked the slide-out animation from 3.38, the thumbnails slided out of the edge when going in overview. Would be nice to bring back.

If you have any pointers where to start I'd be happy to contribute.

**Comment by RensAlthuis** [comment]
@romgrk Yeah, I'd like to bring the sliding animation back too. And I would love to get some help!
All the things mentioned here can probably be fixed in the thumbnails box allocation: https://github.com/RensAlthuis/vertical-overview/blob/33e0fe4d274c68f09428b1c9e4a41102977f72b0/workspaceThumbnail.js#L126

Though sliding in from the side might have to happen in animateToOverview:
https://github.com/RensAlthuis/vertical-overview/blob/33e0fe4d274c68f09428b1c9e4a41102977f72b0/CurrentOriginals/overviewControls.js#L652

**Comment by RensAlthuis** [comment]
Centered workspace thumbnails are implemented in f98f233, I'm closing this issue now. @romgrk If you want you can open new issues for the other requests.
