### ISSUE TITLE
trouble installing

### ISSUE THREAD

**Issue by eeshugerman** [RensAlthuis/vertical-overview#24]
here's my attempt
```
➜ make
if test  -d _build; then rm -r _build; fi
glib-compile-schemas ./schemas
zip -r vertical-overview@RensAlthuis.github.com * -x Makefile
  adding: dash.js (deflated 73%)
  adding: extension.js (deflated 76%)
  adding: gestures.js (deflated 80%)
  adding: LICENSE (deflated 66%)
  adding: metadata.json (deflated 38%)
  adding: overviewControls.js (deflated 78%)
  adding: prefs.js (deflated 63%)
  adding: README.md (deflated 41%)
  adding: schemas/ (stored 0%)
  adding: schemas/org.gnome.shell.extensions.vertical-overview.gschema.xml (deflated 77%)
  adding: schemas/gschemas.compiled (deflated 43%)
  adding: settings.ui (deflated 91%)
  adding: stylesheet.css (deflated 60%)
  adding: swipeTracker.js (deflated 79%)
  adding: util.js (deflated 63%)
  adding: workspace.js (deflated 69%)
  adding: workspacesView.js (deflated 72%)
  adding: workspaceThumbnail.js (deflated 73%)
mkdir _build
mv vertical-overview@RensAlthuis.github.com _build/

➜ make install
gnome-extensions install -f ./_build/vertical-overview@RensAlthuis.github.com

# at this point i logged out and back in

➜ gnome-extensions enable vertical-overview@RensAlthuis.github.com

Extension “vertical-overview@RensAlthuis.github.com” does not exist

```

Using Wayland. Let me know if there's any more info I can provide.

**Comment by RensAlthuis** [comment]
Strange, can you check ``~/.local/share/gnome-shell/extensions/`` and see if ``vertical-overview@RensAlthuis.github.com folder exists``? If it does remove it and try again. Otherwise you could try creating the folder and manually unpack the zip file from ``_build`` to that folder.

Alternatively, if you just want an easy fix I've recently gotten the extension published on the official site:
https://extensions.gnome.org/extension/4144/vertical-overview/

**Comment by eeshugerman** [comment]
>can you check `~/.local/share/gnome-shell/extensions/` and see if `vertical-overview@RensAlthuis.github.com` folder exists? If it does remove it and try again.

It was there; this worked! But I'll probably switch to the extensions.gnome.org approach anyway.

Thanks for the help, and for this project!
